### ISSUE TITLE
Iridion II crashes on undefined Opcode

### ISSUE THREAD

**Issue by zenseii** [Gericom/GBARunner3#36]
The game crashes on various points in-game. Getting to these points in no$gba shows warning about undefined opcode:
<details>
<summary>no$gba Screenshot</summary>

![image](https://github.com/Gericom/GBARunner3/assets/12501091/451dc778-8381-42f0-ba85-c4de83a08e29)

</details>

Attached savestate from no$gba debug version. Get to the boss and watch the warning kick in after a few seconds. Same place triggers it in GBARunner3.

[IridionIIPreBossStage2.zip](https://github.com/Gericom/GBARunner3/files/12851024/IridionIIPreBossStage2.zip)

In GBARunner3 you can use the password 4RC8! and enter challenge mode to test this.

**Comment by Dartz150** [comment]
I've tested this with the latest commit bb9c06b + manual JIT patches and the described issue is still happening.

[AI2E00.json](https://github.com/Gericom/GBARunner3/files/13432908/AI2E00.json)

**Comment by Dartz150** [comment]
This also happened on mGBA at some point, it seems that this game has an AP measure that checks for existing save-data functions/files, which shouldn't be on a real game since it uses a Password system instead.

https://github.com/mgba-emu/mgba/issues/196

Adding a save override option for this game to not save could fix it.
